name: courses_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^5.6.2
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_storage: ^12.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_otp_text_field: ^1.4.0+2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  go_router: ^14.6.3
  google_api_availability: ^5.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  meta: ^1.9.1
  numeric_keyboard: ^1.1.0
  percent_indicator: ^4.2.4
  permission_handler: ^11.3.1
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/png/
