// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXgBCbojDW63Rw_Qso67YkM2L7OjCsjvI',
    appId: '1:18639900252:web:69945e1e7884bb647ba099',
    messagingSenderId: '18639900252',
    projectId: 'courses-app-688d5',
    authDomain: 'courses-app-688d5.firebaseapp.com',
    storageBucket: 'courses-app-688d5.firebasestorage.app',
    measurementId: 'G-X59R00CS60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5nv0NVfy0jZarR1O7Zdi836wWL5HxUR4',
    appId: '1:18639900252:android:16eafb5ec3917c047ba099',
    messagingSenderId: '18639900252',
    projectId: 'courses-app-688d5',
    storageBucket: 'courses-app-688d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE_DALlsWiaQSnKuQ9pC5GlHLjyHeG60Q',
    appId: '1:18639900252:ios:8e2edc69a9973c397ba099',
    messagingSenderId: '18639900252',
    projectId: 'courses-app-688d5',
    storageBucket: 'courses-app-688d5.firebasestorage.app',
    iosBundleId: 'com.example.coursesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE_DALlsWiaQSnKuQ9pC5GlHLjyHeG60Q',
    appId: '1:18639900252:ios:8e2edc69a9973c397ba099',
    messagingSenderId: '18639900252',
    projectId: 'courses-app-688d5',
    storageBucket: 'courses-app-688d5.firebasestorage.app',
    iosBundleId: 'com.example.coursesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXgBCbojDW63Rw_Qso67YkM2L7OjCsjvI',
    appId: '1:18639900252:web:aae0972bfb60c5637ba099',
    messagingSenderId: '18639900252',
    projectId: 'courses-app-688d5',
    authDomain: 'courses-app-688d5.firebaseapp.com',
    storageBucket: 'courses-app-688d5.firebasestorage.app',
    measurementId: 'G-QT11NS3SRM',
  );
}
